
name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  # Core
  uuid: ^4.5.2
  intl: ^0.18.1
  shared_preferences: ^2.5.4 # For local storage
  path_provider: ^2.1.1
  
  # State Management (Recommended: Riverpod for simplicity & power)
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI
  fl_chart: ^0.66.0 # For Charts (Bar, Pie)
  lucide_icons_flutter: ^3.1.8
  
  # Backend
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  
  # Other existing dependencies I'll keep
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  collection: ^1.19.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic

